name: ren2date
version: '1.0.2'
summary: Rename files with predefined or custom time stamps
description: |
  Ren2Date is an easy to use flexible time stamping tool
  
  Whether is logs, exports, statements, or other data where you wish to
  rename the file with a specific time stamp, Ren2Date is the utility for you.
  
  You can rename based on a pre-defined template, or use a any custom format you wish.
  Please see the homepage for additional information.
  
  HomePage:  https://github.com/frossm/ren2date

grade: stable
confinement: strict
base: core22

title: Ren2Date
website: https://github.com/frossm/ren2date
issues: https://github.com/frossm/ren2date/issues
icon: graphics/PostIt-512.jpg
license: MIT

# Enable faster LZO compression
compression: lzo

# Ignore useless library warnings
lint:
  ignore:
    - library

apps:
  ren2date:
    command: ren2date-wrapper
    plugs:
       - network
       - home

parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local

  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-type: git
    source-tag: 'v2024.01.22'
    maven-parameters:
       - install

    build-packages:
      - maven
      - openjdk-11-jdk-headless

  ren2date:
    plugin: maven
    source: https://github.com/frossm/ren2date.git
    source-branch: master
    source-type: git
    after:
       - library

    build-packages:
      - maven
      - openjdk-11-jdk-headless

    stage-packages:
      - openjdk-11-jre-headless

    override-prime: |
      snapcraftctl prime
      rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs
