name: ren2date
title: Ren2Date
version: '2.1.1'
summary: Rename files with predefined or custom time stamps
description: |
  Ren2Date is an easy to use flexible time stamping tool
  
  Whether is logs, exports, statements, or other data where you wish to
  rename the file with a specific time stamp, Ren2Date is the utility for you.
  
  You can rename based on a pre-defined template, or use a any custom format you wish.
  Please see the homepage for additional information.
  
  HomePage:  https://github.com/frossm/ren2date

grade: stable
confinement: strict
base: core24
type: app

website: https://github.com/frossm/ren2date
contact: ren2date@fross.org
issues: https://github.com/frossm/ren2date/issues
icon: graphics/PostIt-512.jpg
license: MIT

platforms:
  amd64:

# Enable faster LZO compression
compression: lzo

lint:
  ignore:
    - library

apps:
  ren2date:
    command: ren2date-wrapper
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-21-openjdk-$CRAFT_ARCH_BUILD_FOR
      PATH: $SNAP/usr/lib/jvm/java-21-openjdk-$CRAFT_ARCH_BUILD_FOR/bin:$PATH

    plugs:
      - network
      - home

parts:
  rpncalc:
    plugin: nil
    source: .
    build-attributes: [ network ]

    override-build: |
      # Ensure that gradlew is executable
      chmod +x gradlew

      # Build the application
      ./gradlew shadowJar -x test --console=plain

      # Move the shadowJar to the right place
      mkdir -p $SNAPCRAFT_PART_INSTALL/jar
      cp build/libs/*.jar $SNAPCRAFT_PART_INSTALL/jar/ren2date.jar

      # Move the wrapper and ensure it's executable
      cp $SNAPCRAFT_PROJECT_DIR/snap/local/ren2date-wrapper $SNAPCRAFT_PART_INSTALL/
      chmod +x $SNAPCRAFT_PART_INSTALL/ren2date-wrapper

    build-packages:
      - gradle
      - openjdk-21-jdk-headless

    stage-packages:
      - openjdk-21-jre-headless
